update cicd

diff --git a/.github/workflows/pretext-cli.yml b/.github/workflows/pretext-cli.yml
--- a/.github/workflows/pretext-cli.yml
+++ b/.github/workflows/pretext-cli.yml
@@ -33,6 +33,16 @@ jobs:
             - name: install local ptx files
               run: pretext --version
 
+            - name: download and unzip cache
+              run: |
+                sudo apt update
+                sudo apt install unzip curl
+                if curl -fLo cache.zip https://stevenclontz.github.io/ptx-online-cache-proof-of-concept/cache.zip; then
+                  unzip -o cache.zip || true
+                else
+                  echo "cache.zip not found, continuing without cache."
+                fi
+
             - name: build deploy targets
               run: |
                 version="$(pretext --version)"
@@ -47,6 +57,14 @@ jobs:
                 fi
             - name: stage deployment
               run: pretext deploy --stage-only
+
+            - name: zip and stage cache
+              run: |
+                sudo apt update
+                sudo apt install zip
+                zip -r cache.zip .cache
+                mkdir -p output/stage/
+                cp cache.zip output/stage/
 
             - name: Bundle output/stage as artifact
               uses: actions/upload-artifact@v4
